### ISSUE TITLE
May I ask if the one you open source is the DeepStuQ model? Why is the code model AGCRN?

### ISSUE THREAD

**Issue by HXF0717** [WeizhuQIAN/DeepSTUQ_Pytorch#2]

**Comment by WeizhuQIAN** [comment]
DeepSTUQ is not exactly a _model_ but an uncertainty quantification method, in which AGCRN serves as the base model (it can be replaced by other appropriate model architectures ). In other words, we are trying to estimate the distributions of the base model's predictions.
Hope this helps,
Best

**Comment by HXF0717** [comment]
Okay, I understand what you mean. Thank you for your reply!
